Several changes regarding backend frontend integration
Rostlab/JS18_ProjectA_Group2 pull request #47
Opened 2018-03-20 02:16 UTC by shayansiddiqui

2018-03-20 04:42 UTC, jyotirmay123 commented
able to resolve the original issue, but now phantomjs browser throws error on testing. It seems it is not able to compile some of es6 keyword like const and => (arrow function ).
To resolve this, I have uncommented all requirements in polyfills.ts, but no luck yet.

2018-03-20 13:48 UTC, syxolk submitted a review, later dismissed

2018-03-20 13:48 UTC, syxolk commented on server/services/DataService.js
> +    return eval(queryString).on("query", function (generated_query) {
This does not seem like a good idea. Why would you build up a string and call `eval` on it? Looks like a huge SQL injection possibility.

2018-03-20 14:23 UTC, shayansiddiqui commented on server/services/DataService.js
> +    return eval(queryString).on("query", function (generated_query) {
This is not actual sql query but knex query which will then be converted to SQL by knex itself and it also takes care of sql injection internally

2018-03-21 13:43 UTC, csehlke approved these changes
looks good to me, the only thing that maybe should be investigated is where the warning comes from

2018-03-21 13:43 UTC, csehlke commented on UI/models/Layout.ts
> +    constructor(title: string) {
that one looks kind of strange to me, can you explain that a bit? Why do we have a title that is not stored anywhere

2018-03-21 13:43 UTC, csehlke commented on UI/src/app/home/home.component.ts
> +import {Data} from "../../../models/Data";
that one can be shortend and combined with the one above

2018-03-21 13:43 UTC, csehlke commented on UI/src/app/chart/chart.component.ts
> +import * as Plotly from 'plotly.js';
I am not sure but maybe this has something to do with this:

```
[WDS] Warnings while compiling.
./node_modules/plotly.js/dist/plotly-basic.js
Module not found: Error: Can't resolve 'vertx' in 'C:\Users\Carsten\Documents\Uni\JS18_ProjectA_Group2\node_modules\plotly.js\dist'
 @ ./node_modules/plotly.js/dist/plotly-basic.js 36873:16-26
 @ ./UI/src/app/chart/chart.component.ts
 @ ./UI/src/app/chart/index.ts
 @ ./UI/src/app/app.module.ts
 @ ./UI/main.ts
 @ multi (webpack)-dev-server/client?http://0.0.0.0:0 ./UI/main.ts
```

2018-03-21 14:24 UTC, csehlke requested changes

2018-03-21 14:24 UTC, csehlke commented on UI/src/app/home/home.component.ts
> -    layout: Layout;
If we remove them in here, we cannot bind them in the html file anymore

2018-03-21 14:27 UTC, csehlke approved these changes

2018-03-21 14:27 UTC, csehlke commented on UI/src/app/home/home.component.ts
> -    layout: Layout;
done

2018-03-21 15:17 UTC, jyotirmay123 commented on server/services/DataService.js
> +    return eval(queryString).on("query", function (generated_query) {
I think this has been resolved. hence dismissing Hans request.

2018-03-21 15:18 UTC, merged

2018-03-21 23:03 UTC, syxolk commented on server/services/DataService.js
> +    return eval(queryString).on("query", function (generated_query) {
This doesn't make sense. The purpose of knex is to build SQL, so why don't you just knex then instead of building a string?