Issue 58 nlp expansion
Rostlab/JS18_ProjectA_Group2 pull request #77
Opened 2018-04-07 22:17 UTC by shayansiddiqui

2018-04-08 00:23 UTC, jyotirmay123 requested changes
Lots of console.logs, could you please remove them or do you need them for further checking?

2018-04-08 07:47 UTC, csehlke requested changes

2018-04-08 07:47 UTC, csehlke commented on server/config.js
> +            password: 'root',
you might want to remove your password again 😄

2018-04-08 07:47 UTC, csehlke commented on server/utils/dictionary.js
> +        "employment_status": ["status", "employee’s sex", "sex of employees", "employee status"],
are you sure that this should be `employes sex` and not status?

2018-04-08 07:47 UTC, csehlke commented on server/utils/dictionary.js
> +        "employment_status": ["status", "employee’s sex", "sex of employees", "employee status"],
and maybe we should add the three phrases also for `gender`

2018-04-08 07:56 UTC, csehlke requested changes
Do we need the folders `projects/my_project` and `projects/test_projects` ?

2018-04-08 08:09 UTC, csehlke requested changes

2018-04-08 08:09 UTC, csehlke commented on UI/src/app/home/home.component.html
> +            <div [hidden]="!disableUpdateTextField()" class="msg-div">
you are abusing those methodes: 
I'd like to have the two text fields to be shown next to each other the whole time, like it was before

other than that the design looks really nice

2018-04-08 08:29 UTC, csehlke reviewed
where did you get the logo from? do we need to credit the author somewhere?

2018-04-08 08:31 UTC, jyotirmay123 approved these changes

2018-04-08 16:59 UTC, csehlke commented on UI/src/app/home/home.component.html
> +            <div [hidden]="!disableUpdateTextField()" class="msg-div">
I fixed it in #81 
maybe you take a look at it and merge it in here

2018-04-08 18:14 UTC, csehlke commented
@shayansiddiqui can you please take a look the comments, so that we could merge this?
I will take care of the merge conflict due to my UI testing commits later this evening

2018-04-09 08:18 UTC, shayansiddiqui commented on UI/src/app/home/home.component.html
> +            <div [hidden]="!disableUpdateTextField()" class="msg-div">
As I understood you were using two diff functions for the same task(showing and hiding of text input and button) thats why I used it. Also the button disableUpdateButton() was not working for me so I used it everywhere. However you are free to experiment with layout!!

2018-04-09 08:29 UTC, shayansiddiqui commented
Can somebody review and approve again?

2018-04-09 08:32 UTC, jyotirmay123 approved these changes
looks good.

2018-04-09 08:33 UTC, iraklitchedia approved these changes
Looks fine

2018-04-09 08:59 UTC, csehlke approved these changes

2018-04-09 08:59 UTC, merged